### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by nagkumar** [makotogo/ChaincodeTutorial#1]
Hi,
Can you pl. check your example code with latest fabic code 

specially the file com.makotojava.learn.blockchain.chaincode.AbstractChaincode

This code seem to be obsolete as ChaincodeBase does not have these methods any more

 @Override
    public String run(ChaincodeStub stub, String function, String[] args)  

&

 @Override
    public String query(ChaincodeStub stub, String function, String[] args)

**Comment by makotogo** [comment]
At the moment, the code in this repository works with Fabric v0.6 only.
